### ISSUE TITLE
 Cannot launch randovania-flatpak after modifications. "bwrap: Can't mkdir /tmp/.X11-unix: Permission denied"

### ISSUE THREAD

**Issue by Dante-tLDS** [flathub/io.github.randovania.Randovania#11]
Hello! I am here to ask for some assistance in fixing an error I believe I had caused with an app not launching. 
Currently, when I try and launch [Randovania](https://flathub.org/apps/io.github.randovania.Randovania) via my terminal, I get this error:
```
$ flatpak run io.github.randovania.Randovania 
bwrap: Can't mkdir /tmp/.X11-unix: Permission denied
```
I do not know how to fix it, as I have attempted to uninstall and reinstall randovania.
This is the only application I have on flatpak that is experiencing this problem.

A history of how I got to here is as such (This may be a bit of reading)
I am using both my Browser and Discord on Flatpak, and had wanted to play Randovania. But I realized that Randovania (from github not flatpak. I'll make it known when the flatpak version comes in play) wasn't opening my browser to log into.
So I asked around and was recommended to enter the current randovania folder and remove a file called `libstdc++.so.6`. So I did, and this almost worked, as when I went to search for a Multiworld in randovania and was prompted to log in, pressing "log in" would attempt to load my browser. But, sadly, randovania returned this error: `/usr/bin/flatpak: symbol lookup error: /usr/lib/libmalcontent-0.so.0: undefined symbol: g_task_set_static_name` 
(it is trying to launch my flatpak browser, but seems to fail)

I had installed the flatpak version of randovania prior to asking around, and had experimented with it prior to knowing that mutliworlds were unsupported, but through this version I was at least able to log into it, I was told this was due to "the flatpak environment ship[ping] the required (outdated) deps", whereas the current github version does not. 

After my attempts with the github version, I had made an attempt that I believe broke the flatpak version of randovania. 
I had tried to move my github-extracted Randovania folder to the one flatpak made to replace it, using a command that looks a lot like this: `mv /home/user/randovania-6.4.1/ /var/lib/flatpak/app/io.github.randovania.Randovania/x86_64/stable/[some giant string]/files/share/`
Prior to this I had also relocated `/var/lib/flatpak/..../files/share/randovania` somewhere else as well, just so I could return it if this didn't work.
After running the command, I then renamed `randovania-6.4.1` to just `randovania` and chowned it as root (as the flatpak folder was also root-owned). Made sure the perms were the same. Though thinking about it, maybe it wasn't wise to make it recursive.

The attempt did not work, it didn't launch (I forget the error it gave, if any).

But now when I moved the (perm unmodified) original folder back, it would not launch still. Giving me the error at the start of the post.
I checked in flatseal, but it tells me that the perms set are their defaults. I cannot remember if there were any directories given to it under Filesystem/Other Files, but as of current they are empty.

So, with this, I ask:
- What can I do to fix Randovania on Flatpak? I uninstalled it, deleted its data where I could find it, and reinstalled it, but to no progress.
- Are there any additional steps for the github version of randovania that would allow it to launch my flatpak-browser and log me in this way? 
I currently have to use a (thankfully preserved) copy of my login instance from flatpak and copy it over to the github login to log into it. If I could figure this out, I would be able to log in using only one variant of Randovania.

Thank you for any help you can provide.

[PC Specs if they help]
- CPU: Ryzen 9 5900x
- Board: Asus x570 Prime-P
- OS: Arch
- FileSystem: Btrfs (with subvolumes `@, @home, @var, @usr, @opt, @swap, @snapshots`)
- Kernel: 6.5.7-hardened1-1-hardened 
- Flatpak Version: 1.15.4 (with bubblewrap-suid as a dependency for Linux Hardened flatpak)
- and if this matters, I ran `chmod u+s /usr/bin/bwrap` which allows flatpak to also work on linux hardened.

**Comment by Dante-tLDS** [comment]
I managed to fix the issue, I missed a spot where flatpak existed (`/run/user/1000/.flatpak/`). Deleting the randovania folder in here and trying to relaunch it seems to have worked. I am not certain if this is the only folder that needed deletion, as I have deleted it from everywhere else beforehand (Deleted flatpak in ~/.cache, ~/.local, and the rando app in ~/.var/apps, then deleted `/var/lib/flatpak/repo/refs/head/deploy/app/io.github.randovania.Randovania/`, then `var/lib/flatpak/repo/refs/remotes/flathub/runtime/io.github.randovania.Randovania/`, even went as far as deleting the icons for it in `/var/lib/flatpak/appstream/flathub/x86_64/`. So many places where flatpak stores stuff xd)

So, tldr: If you mess up an app like I did, try this:
- Remove `/run/user/1000/.flatpak/io.github.randovania.Randovania/` as root, and try re-launching it.
If it works, great. If not, repeat and delete these too:
[Home folders]
- `~/.cache/flatpak/`
- `~/.local/flatpak/`
- `~/.var/app/io.github.randovania.Randovania/`
[Root folders]
- `/var/lib/flatpak/repo/refs/head/deploy/app/io.github.randovania.Randovania/`
- `/var/lib/flatpak/repo/refs/remotes/flathub/runtime/io.github.randovania.Randovania/`
I should note that when deleting all of these, you should likely have Randovania flatpak-uninstalled
(I don't think you need to delete the icons folder like I did. That was unnecessary probably. Additionally, don't delete `/tmp/X11-unix`, that isn't gonna fix it. Also don't delete `/var/lib/flatpak/repo/tmp/` (maybe something within, but not the whole thing), this did not work either. Had to re-create both of those)
I did also uninstall/reinstall flatpak as a whole and then reinstalled the flathub remotes, but since that didn't work I'm going to assume this wasn't necessary either.

I am still completely open to hearing suggestions for question 2 of my first post however, as that would certainly still be helpful

**Comment by Miepee** [comment]
Question is about the GH release, not the flatpak release. So it's at the wrong place here.
